import { Company } from './company';

export const COMPANIES : Company[] = [
    {
        id: 1,
        companyname: 'IBM',
        turnover: 1,
        ceo: 'Yolanda',
        directors: 'www',
        stockexchanges: 'BSE',
        sector: 'CCC',
        brief: 'KKMNJDD',
        stockcode:'123',
        companystatus:'confirm',
    },
    {
        id: 2,
        companyname: 'CA',
        turnover: 2,
        ceo: 'Anne',
        directors: 'www',
        stockexchanges: 'NSE',
        sector: 'CCC',
        brief: 'KKMNJDD',
        stockcode:'456',
        companystatus:'confirm',
    },
    {
        id: 3,
        companyname: 'CA',
        turnover: 3,
        ceo: 'Anne',
        directors: 'www',
        stockexchanges: 'NSE',
        sector: 'CCC',
        brief: 'KKMNJDD',
        stockcode:'456',
        companystatus:'confirm',
    },
    {
        id: 4,
        companyname: 'CA',
        turnover: 4,
        ceo: 'Anne',
        directors: 'www',
        stockexchanges: 'NSE',
        sector: 'CCC',
        brief: 'KKMNJDD',
        stockcode:'456',
        companystatus:'confirm',
    },
];